### PR TITLE
Build on Win32

### PR DESCRIPTION
**Pull request by gcasa**
Add instructions for building on windows.  Also make changes to build.sh and other files to build

### CODE REVIEW

**Comment by fhgwright** [comment]
I only meant "fork" for this repo in the GitHub sense of "fork", though that's actually not possible in this case since the primary repo isn't on GitHub.  I've updated the description to clarify.  It's not my intention for this to be a version of the code diverging from the primary repo.

I've emailed the owner of the code, and suggested how he might obtain the changes from here.  He may respond here.

BTW, do you know about "squash"?  14 separate commits seems like a lot for such a change.

**Comment by mmcmaster-au** [comment]
Hi,

I won't be adding this patch to my git repo as I don't wish to support people trying to compile on Windows.

scsi2sd-util is being phased out in favour of a java application with a better UI. I've just uploaded the current app to http://www.codesrc.com/gitweb/index.cgi?p=scsi2sd-util.git;a=summary

**Comment by mmcmaster-au** [comment]
There's a windows version at http://www.codesrc.com/files/tmp/scsi2sd-util-1.0.msi

**Comment by gcasa** [comment]
Original author doesn't want this patch.  Closing.

**Pull request closed without merging**
